# Site configuration
  title: mblo
  description: >
    Web developer blog, inside, Magento, Php, Javascript and more. 
    Information submitted in small articles on interesting topics.
  url: "http://evgv.github.io"
  date_format: '%B %d, %Y'
  fort_awesome_icon: 'cog fa-spin'

# Owner configuration
  owner:
    name: Evgen Zubkov
    email: evgvzubkoff@gmail.com
    github: evgv
    twitter: evgvzubkoff
    linkedin: 
    facebook:
    google_plus:
    youtube:

# Post sharing icons
  sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
  disqus_shortname: 'evgvgithubio'

# Markdown
  markdown: kramdown
