# Site settings
title: mblo
email: evgvzubkoff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web developer blog, inside, Magento, Php, Javascript and more. 
  Information submitted in small articles on interesting topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evgv.github.io" # the base hostname & protocol for your site
twitter_username: evgvzubkoff
github_username:  evgv

# Build settings
markdown: kramdown
